spring:
  application:
    name: product-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
server:
  port: 0