spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/inventory_service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

server:
  port: 8082
