server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-inventory:5432/inventory-service
    driver-class-name: org.postgresql.Driver
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka